name: Git username and email config
runs:
  using: composite
  steps:
    - run: |
        git config --local user.name "${{ github.actor }}"
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
      shell: bash
