name: "Bump version and create draft release"
on:
  workflow_dispatch:
    inputs:
      field:
        description: "Version field to bump"
        type: choice
        options:
          - patch
          - minor
          - major
        required: true
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          npm version ${{ inputs.field }}
          git push
          git push --tags
          gh release create $(git describe) -d --latest --verify-tag --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
