name: "Create PR for new SQLite version"
on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL suffix (e.g. 2022/sqlite-amalgamation-3400000.zip)"
        required: true
      hash:
        description: "Archive hash"
        required: true
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - run: |
          import re, os
          v = re.search(r'amalgamation-(\d+)\.zip', '${{ inputs.url }}').group(1)
          version = f'{int(v[0])}.{int(v[1:3])}.{int(v[3:5])}'
          with open(os.getenv('GITHUB_ENV'), 'a') as file:
            file.write(f'version={version}\n')
            file.write(f'branch=update-sqlite-{version}\n')
        shell: python
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: "! git checkout ${{ env.branch }} -- # branch already exists?"
      - run: |
          perl -pi -e "s|^(\s*SQLITE_URL\s*=\s*).*|\${1}https://www.sqlite.org/${{ inputs.url }}|" Makefile
          perl -pi -e "s|^(\s*SQLITE_HASH\s*=\s*).*|\${1}${{ inputs.hash }}|" Makefile
      - uses: ./.github/actions/create-pr
        with:
          branch: ${{ env.branch }}
          message: "Update to SQLite ${{ env.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
