name: "Create PR for new SQLite version"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g. 3400100)"
        required: true
      hash:
        description: "Archive hash"
        required: true
      url:
        description: "URL suffix"
        required: true
jobs:
  check:
    outputs:
      exists: ${{ steps.check.outputs.exists }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: check
        run: |
          lines=$(git ls-remote --heads origin update-sqlite-${{ inputs.version }} | wc -l)
          echo "exists=$lines" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  create-pr:
    needs: check
    if: needs.check.outputs.exists == '0'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          perl -pi.bak -e "s|^SQLITE_FOLDER\s*=.*|SQLITE_FOLDER = sqlite-amalgamation-${{ inputs.version }}|" Makefile
          perl -pi.bak -e "s|^SQLITE_URL\s*=.*|SQLITE_URL = https://www.sqlite.org/${{ inputs.url }}|" Makefile
          perl -pi.bak -e "s|^SQLITE_HASH\s*=.*|SQLITE_HASH = ${{ inputs.hash }}|" Makefile
          rm Makefile.bak
      - run: |
          npm run clean
          npm run build
      - uses: ./.github/actions/create-pr
        with:
          branch: update-sqlite-${{ inputs.version }}
          message: "Update to SQLite ${{ inputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
