name: Tests
on:
  workflow_dispatch:
  pull_request:
    types: [assigned]
  push:
    branches:
      - "*"
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11, macos-12]
        node-version: [16.x, 18.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm clean-install
      - run: npm test
